package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-24T15:57:36.528+02:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "StockQuoteHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StockQuoteHttpGet {

    /**
     * Get Stock quote for a company Symbol
     */
    @WebMethod(operationName = "GetQuote")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET/", partName = "Body")
    public String getQuote(
            @WebParam(partName = "symbol", name = "symbol", targetNamespace = "")
            String symbol
    );
}
