FROM anapsix/alpine-java
MAINTAINER Brian Elvesæter <brian.elvesater@sintef.no>

COPY target/webservice-riglogger-1.0-SNAPSHOT.jar /home/webservice-riglogger.jar
CMD ["java", "-jar", "/home/webservice-riglogger.jar"]
